default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/primary.sqlite3
  readonly:
    <<: *default
    database: db/readonly.sqlite3
